networks:
  d2ray_br:
    external: false

services:
  d2ray:
    image: narocat/d2ray
    container_name: d2ray
    ports:
      - 443:443
    environment:
      - HOST=myboardnaro.azurewebsites.net
      - PORT=443
      - TARGET_HOST=www.amazon.com
      - TARGET_PORT=443
      - TARGET_SNI=www.amazon.com
      - USERS=alice,bob,eve
      - PRIVATE_KEY=uJ0MhKbunVS1l0r-g1DgvbtAhWwQva_ACVKNeVHpn34
      - LOG_LEVEL=warn
    restart: unless-stopped
    networks:
      - d2ray_br
    volumes:
      - ./config:/etc/d2ray
